/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/posts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * 投稿を新規作成
		 * @description 避難所の状況を投稿し、必要に応じて災害発生時刻・位置情報の時系列データ・メディアファイル情報を添付します。
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreatePostRequest"];
				};
			};
			responses: {
				/** @description 投稿を作成しました */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CreatePostResponse"];
					};
				};
				/** @description リクエスト内容が不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 避難所一覧を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 避難所一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterListWithCountResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 避難所の詳細を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description 避難所ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 避難所の詳細を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterDetails"];
					};
				};
				/** @description 不正な避難所IDが指定されました */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters/{id}/posts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 指定した避難所の最新投稿を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description 避難所ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 最新の投稿一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterPostsResponse"];
					};
				};
				/** @description 不正な避難所IDが指定されました */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/posts/{id}/comments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** コメントを新規投稿 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description コメント対象の投稿ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreateCommentRequest"];
				};
			};
			responses: {
				/** @description コメントを作成しました */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CreateCommentResponse"];
					};
				};
				/** @description リクエスト内容が不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description 対象の投稿が見つかりません */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		CreatePostRequest: {
			/** @description 投稿対象の避難所ID */
			shelterId: number;
			/** @description 投稿者の表示名 */
			authorName: string;
			/** @description 投稿本文 */
			content?: string | null;
			/**
			 * Format: date-time
			 * @description 投稿時刻（未指定時はサーバー時刻を使用）
			 */
			postedAt?: string | null;
			/**
			 * Format: date-time
			 * @description 災害等の事象が発生した時刻
			 */
			occurredAt?: string | null;
			/**
			 * @description 現在の状況ステータス
			 * @enum {string|null}
			 */
			status?: "緊急" | "重要" | "通常" | null;
			/** @description 動画撮影などに合わせて取得した位置情報の時系列データ */
			locationTrack?: components["schemas"]["LocationTrackPoint"][];
			/** @description 添付するメディア情報 */
			media?: components["schemas"]["PostMediaItem"][];
		};
		LocationTrackPoint: {
			/**
			 * Format: date-time
			 * @description 位置情報を取得した時刻
			 */
			recordedAt: string;
			/**
			 * Format: float
			 * @description 緯度
			 */
			latitude: number;
			/**
			 * Format: float
			 * @description 経度
			 */
			longitude: number;
		};
		PostMediaItem: {
			/** @description MIMEタイプ */
			mediaType: string;
			/** @description メディア表示名 */
			fileName?: string | null;
		};
		CreatePostResponse: {
			post: {
				/** @description 作成された投稿ID */
				id: string;
				/** @description 投稿者の表示名 */
				authorName: string;
				/** @description 投稿対象の避難所ID */
				shelterId: number;
				/** @description 投稿本文 */
				content?: string | null;
				/**
				 * Format: date-time
				 * @description 投稿時刻
				 */
				postedAt: string;
				/**
				 * Format: date-time
				 * @description サーバーでの作成時刻
				 */
				createdAt: string;
				/**
				 * Format: date-time
				 * @description 災害等の事象が発生した時刻
				 */
				occurredAt?: string | null;
				/**
				 * @description 現在の状況ステータス
				 * @enum {string|null}
				 */
				status?: "緊急" | "重要" | "通常" | null;
				/** @description 保存された位置情報の時系列データ */
				locationTrack?: components["schemas"]["LocationTrackPoint"][];
				/** @description 添付されたメディア情報 */
				media?: components["schemas"]["PostMediaItem"][];
			};
		};
		CreateCommentRequest: {
			/** @description コメント投稿者の表示名 */
			authorName: string;
			/** @description コメント本文 */
			content: string;
		};
		CreateCommentResponse: {
			comment: {
				/** @description コメントID */
				id: string;
				/** @description 紐づく投稿ID */
				postId: string;
				/** @description コメント投稿者の表示名 */
				authorName: string;
				/** @description コメント本文 */
				content: string;
				/**
				 * Format: date-time
				 * @description コメントの作成時刻
				 */
				createdAt: string;
			};
		};
		ShelterListWithCountResponse: {
			/** @description 登録されている避難所の総数 */
			shelterCount: number;
			/** @description 避難所の一覧 */
			shelterList: components["schemas"]["ShelterSummary"][];
		};
		ShelterSummary: {
			id: number;
			name: string;
		};
		ShelterDetails: {
			id: number;
			name: string;
			address: string;
			/** Format: float */
			latitude: number;
			/** Format: float */
			longitude: number;
			/** Format: date-time */
			created_at: string;
		};
		ShelterPostsResponse: {
			shelterId: number;
			posts: components["schemas"]["ShelterPost"][];
		};
		ShelterPost: {
			id: string;
			author_name: string;
			content?: string | null;
			/** Format: date-time */
			posted_at: string;
			shelter_name: string;
			comment_count: number;
		};
		ErrorResponse: {
			error: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
