/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/geocode/reverse": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * 緯度・経度から住所を取得
		 * @description Yahoo!地図APIの逆ジオコーダを呼び出し、住所と補助情報を返します。
		 */
		get: {
			parameters: {
				query: {
					/** @description 検索対象の緯度 */
					lat: number;
					/** @description 検索対象の経度 */
					lon: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 住所を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ReverseGeocoderResponse"];
					};
				};
				/** @description 緯度または経度が不足しています */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description 住所が見つかりませんでした */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー内またはYahoo! APIへの問い合わせでエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sync/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * 同期ステータスを取得
		 * @description 未同期データの統計情報を取得します。
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 同期ステータスを取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["SyncStatusResponse"];
					};
				};
				/** @description サーバーエラー */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sync/execute": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * 同期を実行
		 * @description ローカルDBの未同期データを本番DBに同期します。
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["SyncExecuteRequest"];
				};
			};
			responses: {
				/** @description 同期を実行しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["SyncExecuteResponse"];
					};
				};
				/** @description リクエストが不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバーエラー */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sync/receive": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * 同期データを受信
		 * @description 他の環境からの同期データを受信してDBに保存します。
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["SyncReceiveRequest"];
				};
			};
			responses: {
				/** @description 同期データを受信・保存しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["SyncReceiveResponse"];
					};
				};
				/** @description サーバーエラー */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sync/logs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * 同期ログ一覧を取得
		 * @description 過去の同期履歴をページネーション形式で取得します。
		 */
		get: {
			parameters: {
				query?: {
					/** @description Filter by shelter ID (optional) */
					shelterId?: number;
					/** @description Page number (starts from 1, default is 1) */
					page?: number;
					/** @description Number of items per page (default is 10) */
					limit?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 同期ログ一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["SyncLogsResponse"];
					};
				};
				/** @description サーバーエラー */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/posts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * 投稿を新規作成（メディア同梱）
		 * @description 本文・時刻・位置トラックなどのメタデータと、画像/動画ファイルを同梱して投稿します。
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"multipart/form-data": {
						metadata: components["schemas"]["CreatePostRequest"];
						/** @description 添付するメディアファイル（画像/動画） */
						mediaFiles?: string[];
					};
				};
			};
			responses: {
				/** @description 投稿を作成しました */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CreatePostResponse"];
					};
				};
				/** @description リクエスト内容が不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description ファイルサイズが許容上限を超えています */
				413: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description 未対応の Content-Type（MIME）です */
				415: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/posts/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * 投稿の詳細を取得
		 * @description 指定した投稿IDの詳細情報（メディアURL含む）を取得します。
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description 投稿ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 投稿の詳細を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["PostDetailResponse"];
					};
				};
				/** @description 投稿が見つかりません */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 避難所一覧を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 避難所一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterListWithCountResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 避難所の詳細を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description 避難所ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 避難所の詳細を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterDetails"];
					};
				};
				/** @description 不正な避難所IDが指定されました */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/**
				 * @description 現在の状況ステータス
				 * @enum {string|null}
				 */
				status: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/shelters/{id}/posts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 指定した避難所の最新投稿を取得 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description 避難所ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description 最新の投稿一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ShelterPostsResponse"];
					};
				};
				/** @description 不正な避難所IDが指定されました */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description データベースのクエリに失敗しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/posts/{id}/comments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** 投稿に紐づくコメント一覧を取得 */
		get: {
			parameters: {
				query?: {
					/** @description フリーチャット投稿の場合は `true` を指定し、関連コメント取得をスキップします */
					isFreeChat?: boolean;
				};
				header?: never;
				path: {
					/** @description 対象の投稿ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description コメント一覧を取得しました */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["PostCommentsResponse"];
					};
				};
				/** @description リクエスト内容が不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/** コメントを新規投稿 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description コメント対象の投稿ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreateCommentRequest"];
				};
			};
			responses: {
				/** @description コメントを作成しました */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CreateCommentResponse"];
					};
				};
				/** @description リクエスト内容が不正です */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description 対象の投稿が見つかりません */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description サーバー側でエラーが発生しました */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		CreatePostRequest: {
			/** @description 投稿対象の避難所ID */
			shelterId: number;
			/** @description 投稿者の表示名 */
			authorName: string;
			/** @description 投稿本文 */
			content?: string | null;
			/**
			 * Format: date-time
			 * @description 災害等の事象が発生した時刻
			 */
			occurredAt?: string | null;
			/**
			 * @description 現在の状況ステータス
			 * @enum {string|null}
			 */
			status?: "緊急" | "重要" | "通常" | null;
			/** @description 動画撮影などに合わせて取得した位置情報の時系列データ */
			locationTrack?: components["schemas"]["LocationTrackPoint"][];
			/** @description 添付するメディア情報 */
			media?: components["schemas"]["PostMediaItem"][];
		};
		LocationTrackPoint: {
			/**
			 * Format: date-time
			 * @description 位置情報を取得した時刻
			 */
			recordedAt: string;
			/**
			 * Format: float
			 * @description 緯度
			 */
			latitude: number;
			/**
			 * Format: float
			 * @description 経度
			 */
			longitude: number;
		};
		PostMediaItem: {
			/** @description MIMEタイプ */
			mediaType: string;
			/** @description メディア表示名 */
			fileName?: string | null;
		};
		/** @description 投稿作成後のレスポンス */
		CreatePostResponse: {
			/** @description 作成された投稿のID */
			postId: string;
			/** @description アップロードされたメディア情報 */
			media: components["schemas"]["MediaItem"][];
		};
		/** @description メディアファイル情報 */
		MediaItem: {
			/** @description メディアID */
			mediaId: string;
			/** @description MIMEタイプ */
			mediaType: string;
			/** @description 元のファイル名 */
			fileName?: string | null;
			/** @description メディアにアクセスするURL */
			url: string;
		};
		/** @description 投稿詳細情報 */
		PostDetailResponse: {
			/** @description 投稿ID */
			id: string;
			/** @description 避難所ID */
			shelterId: number;
			/** @description 避難所名 */
			shelterName?: string;
			/** @description 投稿者の表示名 */
			authorName: string;
			/** @description 投稿本文 */
			content?: string | null;
			/**
			 * Format: date-time
			 * @description 災害等の事象が発生した時刻
			 */
			occurredAt?: string | null;
			/**
			 * Format: date-time
			 * @description 投稿された時刻
			 */
			postedAt: string;
			/**
			 * @description 現在の状況ステータス
			 * @enum {string|null}
			 */
			status?: "緊急" | "重要" | "通常" | null;
			/** @description 添付されたメディア情報 */
			media: components["schemas"]["MediaItem"][];
			/** @description 位置情報の時系列データ */
			locationTrack?: components["schemas"]["LocationTrackPoint"][];
			/** @description コメント数 */
			commentCount: number;
		};
		OkResponse: {
			/**
			 * @description 処理結果の簡易メッセージ
			 * @example OK
			 */
			message: string;
		};
		CreateCommentRequest: {
			/** @description コメント投稿者の表示名 */
			authorName: string;
			/** @description コメント本文 */
			content: string;
			/**
			 * @description コメントに紐づく状況ステータス
			 * @enum {string|null}
			 */
			status?: "未対応" | "対応中" | "対応済み" | null;
		};
		CreateCommentResponse: {
			comment: {
				/** @description コメントID */
				id: string;
				/** @description 紐づく投稿ID */
				postId: string;
				/** @description コメント投稿者の表示名 */
				authorName: string;
				/** @description コメント本文 */
				content: string;
				/**
				 * Format: date-time
				 * @description コメントの作成時刻
				 */
				createdAt: string;
				/**
				 * @description コメントに紐づく状況ステータス
				 * @enum {string|null}
				 */
				status?: "未対応" | "対応中" | "対応済み" | null;
			};
		};
		PostComment: {
			/** @description コメントID */
			id: string;
			/** @description コメント投稿者の表示名 */
			authorName: string;
			/** @description コメント本文 */
			content: string;
			/**
			 * Format: date-time
			 * @description コメントの作成時刻
			 */
			createdAt: string;
			/**
			 * @description コメントに紐づく状況ステータス
			 * @enum {string|null}
			 */
			status?: "未対応" | "対応中" | "対応済み" | null;
		};
		PostCommentsResponse: {
			/** @description 対象の投稿ID */
			postId: string;
			/**
			 * @description 現在の状況ステータス
			 * @enum {string|null}
			 */
			status?: "緊急" | "重要" | "通常" | null;
			/** @description 対象の投稿がフリーチャットの場合は true */
			isFreeChat?: boolean;
			/** @description コメント一覧 */
			comments: components["schemas"]["PostComment"][];
		};
		ShelterListWithCountResponse: {
			/** @description 登録されている避難所の総数 */
			shelterCount: number;
			/** @description 避難所の一覧 */
			shelterList: components["schemas"]["ShelterSummary"][];
		};
		ShelterSummary: {
			id: number;
			name: string;
			address?: string | null;
			/** Format: float */
			latitude?: number | null;
			/** Format: float */
			longitude?: number | null;
		};
		ShelterDetails: {
			id: number;
			name: string;
			address: string;
			/** Format: float */
			latitude: number;
			/** Format: float */
			longitude: number;
			/** Format: date-time */
			created_at: string;
		};
		ShelterPostsResponse: {
			shelterId: number;
			posts: components["schemas"]["ShelterPost"][];
		};
		ShelterPost: {
			id: string;
			author_name: string;
			content?: string | null;
			/** Format: date-time */
			posted_at: string;
			address?: string | null;
			comment_count: number;
			/**
			 * @description 現在の状況ステータス
			 * @enum {string|null}
			 */
			status?: "緊急" | "重要" | "通常" | null;
		};
		/** @description Yahoo!地図API 逆ジオコーダのレスポンス（Feature 配列）。 */
		ReverseGeocoderResponse: {
			/** @description 位置情報にマッチした候補の一覧 */
			Feature: components["schemas"]["ReverseGeocoderFeature"][];
		};
		ReverseGeocoderFeature: {
			/** @description この候補の代表名称（住所など） */
			Name: string;
			Geometry: components["schemas"]["ReverseGeocoderGeometry"];
			Property: components["schemas"]["ReverseGeocoderProperty"];
		};
		ReverseGeocoderGeometry: {
			/** @description 経度,緯度 の文字列（CSV形式） */
			Coordinates: string;
			/** @description Geometryの種類（通常はPoint） */
			Type: string;
			/** @description 逆ジオコーダが使用した範囲（左下,右上） */
			BoundingBox?: string | null;
		};
		ReverseGeocoderProperty: {
			/** @description 返却された住所テキスト */
			Address: string;
			Country?: string | null;
			Prefecture?: string | null;
			City?: string | null;
			Town?: string | null;
			Street?: string | null;
			Postal?: string | null;
			MatchCode?: string | null;
			MatchLevel?: string | null;
			/** @description 住所の階層ごとの要素 */
			AddressElement?: components["schemas"]["ReverseGeocoderAddressElement"][];
		};
		ReverseGeocoderAddressElement: {
			/** @description 要素の名前（例:Country, City） */
			Name: string;
			NameCode?: string | null;
			/** @description 要素に対応する値 */
			Value: string;
		};
		ErrorResponse: {
			error: string;
		};
		/** @description 同期ステータスのレスポンス */
		SyncStatusResponse: {
			/** @description 未同期の投稿数 */
			unsyncedPosts: number;
			/** @description 未同期のコメント数 */
			unsyncedComments: number;
			/** @description 未同期の位置情報トラック数 */
			unsyncedLocationTracks: number;
			/** @description 未同期データの合計数 */
			totalUnsynced: number;
			/**
			 * Format: date-time
			 * @description 最後に同期した日時
			 */
			lastSyncAt?: string | null;
			/** @description 最後の同期ステータス */
			lastSyncStatus?: string | null;
		};
		/** @description 同期実行リクエスト */
		SyncExecuteRequest: {
			/** @description 同期先のAPI URL */
			targetUrl: string;
			/** @description 避難所ID（オプション） */
			shelterId?: number | null;
		};
		/** @description 同期実行レスポンス */
		SyncExecuteResponse: {
			/** @description 同期が成功したかどうか */
			success: boolean;
			/** @description 同期した投稿数 */
			postsSynced: number;
			/** @description 同期したコメント数 */
			commentsSynced: number;
			/** @description 同期した位置情報トラック数 */
			locationTracksSynced: number;
			/** @description 追加のメッセージ */
			message?: string | null;
			/** @description エラーメッセージ（失敗時） */
			error?: string | null;
		};
		/** @description 同期データ受信リクエスト */
		SyncReceiveRequest: {
			/** @description 同期する投稿データ */
			posts: components["schemas"]["UnsyncedPost"][];
			/** @description 同期するコメントデータ */
			comments: components["schemas"]["UnsyncedComment"][];
			/** @description 同期する位置情報トラックデータ */
			locationTracks: components["schemas"]["UnsyncedLocationTrack"][];
			/** @description 同期元のURL */
			sourceUrl?: string | null;
		};
		/** @description 同期データ受信レスポンス */
		SyncReceiveResponse: {
			/** @description 受信・保存が成功したかどうか */
			success: boolean;
			/** @description 保存した投稿数 */
			postsSynced: number;
			/** @description 保存したコメント数 */
			commentsSynced: number;
			/** @description 保存した位置情報トラック数 */
			locationTracksSynced: number;
			/** @description エラーメッセージ（失敗時） */
			error?: string | null;
		};
		/** @description 未同期の投稿データ */
		UnsyncedPost: {
			id: string;
			author_name: string;
			shelter_id: number;
			content?: string | null;
			/** Format: float */
			latitude: number;
			/** Format: float */
			longitude: number;
			/** Format: date-time */
			posted_at: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
			is_free_chat: number;
			status?: string | null;
		};
		/** @description 未同期のコメントデータ */
		UnsyncedComment: {
			id: string;
			post_id: string;
			author_name: string;
			content: string;
			status: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		/** @description 未同期の位置情報トラックデータ */
		UnsyncedLocationTrack: {
			id: string;
			post_id: string;
			/** Format: date-time */
			recorded_at: string;
			/** Format: float */
			latitude: number;
			/** Format: float */
			longitude: number;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		/** @description 同期ログ一覧のレスポンス */
		SyncLogsResponse: {
			/** @description 同期ログのリスト */
			logs: components["schemas"]["SyncLogItem"][];
			/** @description 総件数 */
			totalCount: number;
			/** @description 現在のページ番号 */
			page: number;
			/** @description 1ページあたりの件数 */
			limit: number;
			/** @description 総ページ数 */
			totalPages: number;
		};
		/** @description 同期ログの詳細情報 */
		SyncLogItem: {
			/** @description 同期ログID */
			id: number;
			/** @description 避難所ID */
			shelterId?: number | null;
			/** @description 避難所名 */
			shelterName?: string | null;
			/** @description 同期タイプ（full, incremental, manual） */
			syncType: string;
			/** @description 同期ステータス（pending, in_progress, completed, failed） */
			status: string;
			/**
			 * Format: date-time
			 * @description 同期開始日時
			 */
			startedAt: string;
			/**
			 * Format: date-time
			 * @description 同期完了日時
			 */
			completedAt?: string | null;
			/** @description 同期された投稿数 */
			postsSynced: number;
			/** @description 同期されたコメント数 */
			commentsSynced: number;
			/** @description 同期された位置情報トラック数 */
			locationTracksSynced: number;
			/** @description 同期された合計件数 */
			totalSynced: number;
			/** @description エラーメッセージ（失敗時） */
			errorMessage?: string | null;
			/** @description 同期先URL */
			targetUrl?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
